AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: faassh, an SSH Server on AWS Lambda
Resources:
  FaasshLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: faassh-net-overlay
      Description: faash server
      ContentUri: ./layer
      CompatibleRuntimes:
        - nodejs8.10
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  FaaServer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 120
      ReservedConcurrentExecutions: 1
      CodeUri: ./lambda
      Environment:
        Variables:
          JUMP_HOST:
          JUMP_HOST_PORT:
          JUMP_HOST_USER:
          KEY_PATH:
          PORT:
          TUNNEL_PORT:
      Layers:
        - !Ref FaasshLayer
